server:
  port: 1101
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root-123
    url: jdbc:mysql://localhost:3306/mahabala
    username: root
  jpa:
    hibernate:
      ddl-auto: update
